apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-kon-rules
  namespace: kon-system
spec:
  groups:
  - name: konstellation-app.rules
