---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konstellation
  namespace: kon-system
  labels:
    control-plane: konstellation-manager
spec:
  selector:
    matchLabels:
      control-plane: konstellation-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: konstellation-manager
    spec:
      serviceAccountName: konstellation
      containers:
      - name: manager
        command:
        - /manager
        args:
        - --enable-leader-election
        image: controller:latest
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
