apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    istio: proxy
  name: istio-proxy
  namespace: istio-system
spec:
  jobLabel: component
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - path: /stats/prometheus
    port: http-envoy-prom
    relabelings:
    - action: labeldrop
      regex: __meta_kubernetes_pod_label_skaffold_dev.*
    - action: labeldrop
      regex: __meta_kubernetes_pod_label_pod_template_hash.*
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
  selector:
    matchExpressions:
    - key: migration
      operator: NotIn
      values:
      - "true"
      - "1"
    matchLabels:
      security.istio.io/tlsMode: istio
