apiVersion: k11n.dev/v1alpha1
kind: App
metadata:
  name: {{ .AppName }}
spec:
  # Docker registry, leave blank if using Docker Hub as your docker registry
  # For other registries, fill in. Docs: https://konstellation.dev/docs/apps/basics#container-registry
  {{- if .Registry }}
  registry: {{ .Registry }}
  {{- else }}
  # registry: registry_url
  {{- end }}
  image: {{ .DockerImage }}
  imageTag: "{{.DockerTag}}"

  # Set command to override the default CMD in your docker image
  # command:
  #   - cmd

  # Arguments to the command
  # args:
  #   - arg

  # Secrets to enable pulling the docker image. The secrets must be created
  # inside each target's namespace
  # imagePullSecrets:
  #   - secretName

  # Port configuration,
  # Change port below to match the port that your app runs on
  # To expose this port on the ingress, reference its name in the ingress section below
  ports:
    - name: http
      port: {{.Port}}

  # Any shared configs your app requires, the app config will be automatically loaded into the env
  # Docs: https://konstellation.dev/docs/apps/configuration#shared-config
  # configs: ['name']

  # Other apps that you depend on, their hostnames will be made available via env vars
  # Docs: https://konstellation.dev/docs/apps/services#connecting-to-services
  # dependencies:
  #   - name: other_app
  #     port: http

  # Service account to use, or a LinkedServiceAccount
  # Docs: https://konstellation.dev/docs/reference/linkedserviceaccount
  # serviceAccount: account-name

  # Define resources that your app requires
  # with CPU, 1000m equals to a single core
  # resources:
  #   requests:
  #     memory: '50Mi'
  #     cpu: '100m'
  #   limits:
  #     memory: '200Mi'
  #     cpu: '200m'

  # Scaling configuration
  # scale:
  #   targetCPUUtilizationPercentage: 60
  #   min: 1
  #   max: 3

  # Probes
  # * liveness: restarts this pod if probe does not return 200
  # * readiness: does not send your pod traffic unless this succeeds
  # probes:
  #   liveness:
  #     httpGet:
  #       path: /running
  #       port: http
  #     periodSeconds: 5
  #     failureThreshold: 3
  #   readiness:
  #     httpGet:
  #       path: /ready
  #       port: http
  #     failureThreshold: 6

  # One or more targets to deploy your app to
  # Each target may also override scale, resources, or probes defined in the app
  # Docs: https://konstellation.dev/docs/apps/basics#targets
  targets:
    - name: {{.Target}}
      # target specific scale overrides app scale
      scale:
        min: 1
        max: 5
      # Uncomment ingress to create a load balancer and/or handle SSL termination for the listed hosts
      # Docs: https://konstellation.dev/docs/apps/basics#ingress
      # ingress:
      #   hosts:
      #     - www.yourhost.com
      #   port: http
          # uncomment to force HTTPS, a 301 redirect will be issued for all HTTP traffic
      #   requireHttps: true
          # additional annotations for the Ingress resource
      #   annotations:
      #     key: value
      # resources:
      # probes:
