# permissions for end users to edit appconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appconfig-editor-role
rules:
- apiGroups:
  - k11n.dev
  resources:
  - appconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k11n.dev
  resources:
  - appconfigs/status
  verbs:
  - get
