# permissions for end users to view appconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appconfig-viewer-role
rules:
- apiGroups:
  - k11n.dev
  resources:
  - appconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k11n.dev
  resources:
  - appconfigs/status
  verbs:
  - get
