# permissions for end users to view apptargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apptarget-viewer-role
rules:
- apiGroups:
  - k11n.dev
  resources:
  - apptargets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k11n.dev
  resources:
  - apptargets/status
  verbs:
  - get
