# permissions for end users to edit apptargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apptarget-editor-role
rules:
- apiGroups:
  - k11n.dev
  resources:
  - apptargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k11n.dev
  resources:
  - apptargets/status
  verbs:
  - get
