# permissions for end users to edit certificaterefs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificateref-editor-role
rules:
- apiGroups:
  - k11n.dev
  resources:
  - certificaterefs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k11n.dev
  resources:
  - certificaterefs/status
  verbs:
  - get
