# permissions for end users to view certificaterefs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificateref-viewer-role
rules:
- apiGroups:
  - k11n.dev
  resources:
  - certificaterefs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k11n.dev
  resources:
  - certificaterefs/status
  verbs:
  - get
