# permissions for end users to edit linkedserviceaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linkedserviceaccount-editor-role
rules:
- apiGroups:
  - k11n.dev
  resources:
  - linkedserviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k11n.dev
  resources:
  - linkedserviceaccounts/status
  verbs:
  - get
