# permissions for end users to view linkedserviceaccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linkedserviceaccount-viewer-role
rules:
- apiGroups:
  - k11n.dev
  resources:
  - linkedserviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k11n.dev
  resources:
  - linkedserviceaccounts/status
  verbs:
  - get
