apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: linkedserviceaccounts.k11n.dev
spec:
  group: k11n.dev
  names:
    kind: LinkedServiceAccount
    listKind: LinkedServiceAccountList
    plural: linkedserviceaccounts
    singular: linkedserviceaccount
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: LinkedServiceAccount is the Schema for the linkedserviceaccounts
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: LinkedServiceAccountSpec defines the desired state of LinkedServiceAccount
          properties:
            policies:
              items:
                type: string
              minItems: 1
              type: array
          required:
          - policies
          type: object
        status:
          description: ConnectedServiceAccountStatus defines the observed state of
            LinkedServiceAccount
          properties:
            awsRoleArn:
              type: string
            linkedTargets:
              items:
                type: string
              type: array
          required:
          - awsRoleArn
          - linkedTargets
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
