apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: builds.k11n.dev
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.registry
    name: Registry
    type: string
  - JSONPath: .spec.image
    name: Image
    type: string
  - JSONPath: .spec.tag
    name: Tag
    type: string
  group: k11n.dev
  names:
    kind: Build
    listKind: BuildList
    plural: builds
    singular: build
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Build is the Schema for the builds API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BuildSpec defines the desired state of Build
          properties:
            createdAt:
              description: Timestamp is a struct that is equivalent to Time, but intended
                for protobuf marshalling/unmarshalling. It is generated into a serialization
                that matches Time. Do not use in Go structs.
              properties:
                nanos:
                  description: Non-negative fractions of a second at nanosecond resolution.
                    Negative second values with fractions must still have non-negative
                    nanos values that count forward in time. Must be from 0 to 999,999,999
                    inclusive. This field may be limited in precision depending on
                    context.
                  format: int32
                  type: integer
                seconds:
                  description: Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z.
                    Must be from 0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z inclusive.
                  format: int64
                  type: integer
              required:
              - nanos
              - seconds
              type: object
            image:
              type: string
            registry:
              type: string
            tag:
              type: string
          required:
          - createdAt
          - image
          - registry
          - tag
          type: object
        status:
          description: BuildStatus defines the observed state of Build
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
