apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ingressrequests.k11n.dev
spec:
  group: k11n.dev
  names:
    kind: IngressRequest
    listKind: IngressRequestList
    plural: ingressrequests
    singular: ingressrequest
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: IngressRequest is the Schema for the ingressrequests API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: IngressRequestSpec defines the desired state of IngressRequest
          properties:
            host:
              type: string
            ports:
              items:
                properties:
                  ingressPath:
                    description: ingressPath indicates the path at which the current
                      port should be exposed. Only for HTTP apps
                    type: string
                  name:
                    type: string
                  port:
                    format: int32
                    type: integer
                  protocol:
                    description: TCP by default. IngressPath works only with HTTP
                      services
                    type: string
                required:
                - name
                - port
                type: object
              type: array
            service:
              type: string
          required:
          - host
          - service
          type: object
        status:
          description: IngressRequestStatus defines the observed state of IngressRequest
          properties:
            message:
              type: string
            status:
              type: string
          required:
          - message
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
