apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appconfigs.k11n.dev
spec:
  additionalPrinterColumns:
  - JSONPath: .type
    name: Type
    type: string
  group: k11n.dev
  names:
    kind: AppConfig
    listKind: AppConfigList
    plural: appconfigs
    singular: appconfig
  scope: Cluster
  subresources: {}
  validation:
    openAPIV3Schema:
      description: AppConfig is the Schema for the appconfigs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        config:
          format: byte
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        type:
          type: string
      required:
      - config
      - type
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
