apiVersion: apps/v1
kind: Deployment
metadata:
  name: konstellation
  namespace: kon-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: konstellation
  template:
    metadata:
      labels:
        name: konstellation
    spec:
      serviceAccountName: konstellation
      containers:
        - name: konstellation
          image: k11n/operator:v0.3.3
          command:
          - konstellation
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "konstellation"
