kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: konstellation
subjects:
- kind: ServiceAccount
  name: konstellation
roleRef:
  kind: Role
  name: konstellation
  apiGroup: rbac.authorization.k8s.io
