apiVersion: k11n.dev/v1alpha1
kind: App
metadata:
  name: app2048
spec:
  image: alexwhen/docker-2048
  ports:
    - name: http
      port: 80
  targets:
    - name: production
      ingress:
        hosts:
          - 2048.mydomain.com
        port: http
        # forwards HTTP requests to HTTPS
        requireHttps: true
        annotations:
          # override to use a custom security policy when using AWS
          # https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-https-listener.html#describe-ssl-policies
          alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-1-2019-08
