apiVersion: k11n.dev/v1alpha1
kind: App
metadata:
  name: myapp
spec:
  image: nginxdemos/hello
  imageTag: latest

  ports:
    - name: http
      port: 80
  resources:
    requests:
      memory: '50Mi'
      cpu: '100m'
    limits:
      memory: '200Mi'
      cpu: '200m'
  scale:
    targetCPUUtilizationPercentage: 60
  probes:
    initialDelaySeconds: 15
    timeoutSeconds: 3
    periodSeconds: 10
    liveness:
      httpGet:
        path: /
        port: http
      failureThreshold: 3
    readiness:
      httpGet:
        path: /
        port: http
      failureThreshold: 6
  targets:
    - name: development
      ingress:
        hosts:
          - davidzhao.com
        port: http
      scale: {min: 1, max: 2}
