apiVersion: k11n.dev/v1alpha1
kind: App
metadata:
  name: myapp
spec:
  registry: registry.hub.docker.com
  image: nginxdemos/hello
  imageTag: latest

  ports:
    - name: http
      port: 80

  env:
    - name: MYVAR
      value: hello world
  resources:
    requests:
      memory: '50Mi'
      cpu: '100m'
    limits:
      memory: '200Mi'
      cpu: '200m'
    scale:
      targetCPUUtilizationPercentage: 60
    probes:
      initialDelaySeconds: 15
      timeoutSeconds: 3
      periodSeconds: 10
      liveness:
        httpGet:
          path: /
          port: 80
        failureThreshold: 3
      readiness:
        httpGet:
          path: /
          port: 80
        failureThreshold: 6
  targets:
    - name: development
      ingress:
        hosts:
          - davidzhao.com
        port: 80
      scale: {min: 1, max: 2}
