apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: kon-grafana
  namespace: grafana
spec:
  ingress:
    enabled: False
  config:
    log:
      mode: "console"
      level: "info"
    security:
      admin_user: "admin"
      admin_password: "admin"
    auth:
      disable_login_form: True
      disable_signout_menu: True
    auth.anonymous:
      enabled: True
  dashboardLabelSelector:
    - matchExpressions:
        - {key: app, operator: In, values: [grafana]}
